### ISSUE TITLE
check if the cap mex feature works for nomads

### ISSUE THREAD

**Issue by Exotic-Retard** [Nomads-Project/nomads#100]
while slinking around in the commmandmode/lua i found this thing:
`
        msid = LetterArray[unit:GetBlueprint().General.FactionName]..'b1106' -- The identity of the storage we'll build`

line 102
might need to be changed to support nomads or maybe we can rename nomads unit files to make it work? dunno lets see.
cos atm we have inb1105 and inb1107? xD

**Comment by speed2CZ** [comment]
Renaming the units to fit the other factions would be the easiest

**Comment by CookieNoob** [comment]
actually mex cap doesnt work for any faction
