### ISSUE TITLE
some textures are failing to load because some stuff gets added to the name

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#102]
INFO: Unable to load texture from file: /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_rest.dds
    INFO: Failed to load 'rest' icon /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_rest.dds
    INFO: Unable to load texture from file: /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_selected.dds
    INFO: Failed to load 'selected' icon /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_selected.dds
    INFO: Unable to load texture from file: /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_over.dds
    INFO: Failed to load 'over' icon /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_over.dds
    INFO: Unable to load texture from file: /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_selectedover.dds
    INFO: Failed to load 'selected over' icon /textures/ui/common/game/strategicicons/icon_artillerysupportprobe1.dds_selectedover.dds

happens on game launch @TheKeyBlue

**Comment by TheKeyBlue** [comment]
Well i fixed the issue with the faulty appending.
But the textures just don't exist.
Not even sure where they are supposed to be used.

**Comment by CookieNoob** [comment]
hm... maybe its an icon related to the intel probe?

**Comment by CookieNoob** [comment]
I suggest to add a "nuke" and an "ACU" icon for these textures and see where they show up. (i.e. copy the texture and rename it to the missing names)

**Comment by CookieNoob** [comment]
so what do we do with this? just merge this change?

**Comment by TheKeyBlue** [comment]
well i fixed an error, so its definitly not bad.
Should i add the acu icon textures?

**Comment by CookieNoob** [comment]
no, I just suggested that to see where these icons are actually used. I didnt spot any icons missing, so I guess it doesnt matter too much.

I tried to copy icon_artillerysupportprobe1.dds and put this texture with the different endings in the folder but I couldnt see any spot where it showed up...

I will push these to this branch and I guess we can merge it afterwards.
