### ISSUE TITLE
ACU orbital bombardment -> rework into nomads tml bombardment

### ISSUE THREAD

**Issue by Ithilis** [Nomads-Project/nomads#103]
It have this nice upgrade on ACU, but its not very nice balance wise. 
Main problem is that this upgrade is not linked primary to ACU unit, where all other acu/sacu upgrades upgrade acu/sacu this will add ability that is somewhere else as on acu. And also missiles fire from one side of map where can/cant be blocked depend on whith side of map enemy is. And another problem is that its hard lock on time, and not on game mechanism as build time of units. And its free of charge where other tml drain resources. And that should be changed. 

My proto concept is that ACU will fire this missiles by own. And will work as acu tml but on nomads bombard style. 

- 5 missile 1500dmg each 1,5aoe (3with capacitator on) 0,25firing randomness (misssile will not hit same place, but aoe will get full dmg in midle) 15-64range  

- single missile cost 45m (200m for salvo) can store them max 5, and fire all stored missile at once

**Comment by CookieNoob** [comment]
I am not against giving the missiles a price, but I would keep the firing mechanism as it is right now.

**Comment by Exotic-Retard** [comment]
me and ithilis discussed this on TS:
it would probably be best for many reasons if the spaceship is brought down lower so its more visible and then made to follow the acu - then the tmls firing from it would be very similar to acu tmls in terms of trajectory and placement. also things like RAS would be given to the ship and not the acu - the acu would only get a resource transfer system on board, just like the TML upgrade, as well as teh base resource generation (+1m +20e) which would be on the ship too.

also it could be interesting to have the intel on the ship as well with the acu having nearly none

all these changes are almost purely visual and from a game point of view its not very different from a regular acu.

**Comment by Ithilis** [comment]
Issue is that maybe it looks nice, but balancewise it will be all time problematic. It fire all time from one position of map what can cause diferent reasult depend on location and you can never change that. 

Half of solution to keep it as this is when mothership is hard link with acu and move with acu. But then its again problem that when missile drain reasources you cant speed up proces. you cant assist to build it faster. And it looks sily to me while only gain is that it looks diferent.

**Comment by CookieNoob** [comment]
moving ras to the ship? to what end? the acu will still display the income so where is the difference??

ok ship can follow the acu, why not

**Comment by Ithilis** [comment]
And what is gain that it alredy have? It fire from spaceship and not acu, why its better?

**Comment by CookieNoob** [comment]
when the space ship is lowered (on the same elevation like the t3 arty sats) and the ship follows the acu, I think the gameplay doesnt suffer from any negative impact and we have one more cool effect. Also faction diversity

**Comment by Exotic-Retard** [comment]
moving ras from the acu to the ship is 99% visual impact, the only thing that changes is the ui when you have the drains on, but it helps us improve the nomads atmosphere, showing whats going on where and such.

**Comment by Ithilis** [comment]
Jast dont move shits into satelite that are pure artifical impact for some more wow..   Keep this space impact as low as posible please :) Seraphim also open interdimensional portals in campain and in multipleyer dont have such think.  Make this change in campain, make it crazy spaceisch but keep multiplayer in fa standards. We will need then expalain and argue about how to implement then and how they fit into fa balance.
