### ISSUE TITLE
Mex - full upgrade path not shown

### ISSUE THREAD

**Issue by Nojoke185** [Nomads-Project/nomads#116]
in base FA game a T1 mex shows the full upgrade path T2 > T3
in nomads it only shows the T2 update

![image](https://cloud.githubusercontent.com/assets/16309355/22589430/391c7f7e-ea02-11e6-9c3f-a7382b583115.png)

**Comment by CookieNoob** [comment]
https://github.com/Nomads-Project/nomads/blob/develop/lua/upgradetemplates.lua#L172

why are we overwriting this file when we dont add the nomad units? xD

**Comment by TheKeyBlue** [comment]
This doesn't work for any of the factions and it doesn't have anything todo with upgrade templates.

The real culprit is an old version of OnSelection in construction.lua 
https://github.com/Nomads-Project/nomads/blob/develop/nomadhook/lua/ui/game/construction.lua#L101
