### ISSUE TITLE
lower orbital units to be better visible

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#117]
it would be best if we lowered the orbital frigate to the same height as the sat from the arty (a bit higher maybe) to make it look like the sat is created by the frigate.

change elevation in INO0001 to a more reasonable elevation. Also adjust the elevation of the arty sat to be comparable with the novax.

suggested values:
arty sat elevation 200 -> 80 
orbital frigate elevation 300 -> 140

**Comment by CookieNoob** [comment]
I kept the frigate higher because it is not much bigger compared to the satellite and otherwise it looks kinda strange.

Interestingly, the arty satellite has a very short build animation where a building beam light flash is send by the frigate. Maybe we can increase the duration of that a little bit.

**Comment by Exotic-Retard** [comment]
you can just increase uniform scale on it, and reason i say this is because with such a huge height its often in your eyeballs
i would actually just decrease the size of the t3 arty sat a little i think its a bit big, - just look at the novax! its tiny!
