### ISSUE TITLE
Rework ACU upgrades so that descriptions of all paths can be seen

### ISSUE THREAD

**Issue by Nojoke185** [Nomads-Project/nomads#120]
In base FA a recent change was made to allow user to hover mouse over each ACU enhancement and see the details (even when a pre-requisite update was not done)
i.e. you can read details for T3 suite even when T2 suite is not added

This change should if possible be carried over and applied to Nomads

![image](https://cloud.githubusercontent.com/assets/16309355/22591629/7d93b130-ea0d-11e6-8fb5-4acdb265624b.png)

**Comment by CookieNoob** [comment]
are you sure that this is not added by the notify mod?

**Comment by Nojoke185** [comment]
pretty sure it was added to base FA. Will see if i can find the original PR

**Comment by Nojoke185** [comment]
looking at the changelog it was introduced in 3654

Patch 3654 (May 30, 2016)
============================
### Reverted
- The change in 3652 which refreshed intel for a blip on upgrade had unintentional free intel side effects we have been unable to solve. As such, that change has been reversed

### UI
- Fixed reductions in MaxHealth resulting in UI displaying 10000/9000 HP
- Added slot numbers in the lobby
- Toggling the shield on a selection of units with a mix of active and inactive shields now toggles them ON instead of OFF
**- The tooltip now shows for ACU and sACU upgrades that are not yet buildable**

**Comment by TheKeyBlue** [comment]
Works for me without any mods.
![upgrade](https://cloud.githubusercontent.com/assets/20644178/22591862/053a4532-ea17-11e6-9f8b-b51fd8d7b7c2.png)

Or what do you mean?

**Comment by Nojoke185** [comment]
sorry think i confused myself
I had mistakenly thought that the change was to also unshadow the unavailable higher tier updates icon
however it looks like it just unlocks the tooltip for them so you can read the tooltip (this was the change made back in 3654) and it looks like it works the same in nomads
I will close this
