### ISSUE TITLE
improve INC0001

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#143]
INC0001 is the landed version of the orbital frigate. It should be improved in some aspects

- add buildbeams to create the initial engies for the start of the mission

- add a transition effect ('takeoff') for the end of the mission

- give the ship the footprint of a large building

- add thruster effect (for the time from "start the engines" to the tml impact)

**Comment by Exotic-Retard** [comment]
uh what xD why would it change elevation?
what did you set the movement type to?

**Comment by CookieNoob** [comment]
jjs_ai said that it would be set to the surface height when you try to build too close to it. I will instead just give it the footprint of an eye of rhianne
