### ISSUE TITLE
Nomad AI doesn't work properly

### ISSUE THREAD

**Issue by JJ173** [Nomads-Project/nomads#158]
Tested the AI: Turtle preset on three different maps with the Nomads selected and they don't work at all. I've been told that CookieNoob's is working but mine isn't. Either way, this'll need looking in to. The AI doesn't even follow a default plan, it just stands there and does nothing.

**Comment by JJ173** [comment]
Pretty big bug in my eyes, hence the high tag.

**Comment by JJ173** [comment]
Tested with @CookieNoob on the test server yesterday to find the AI does work but every variation of the AI uses the same plan.

**Comment by CookieNoob** [comment]
so to clarify, it wasnt us, who broke it btw:
http://forums.faforever.com/viewtopic.php?f=15&t=10215

**Comment by JJ173** [comment]
The AI defaults to the same file no matter what you choose. If you test FAF AI without the Nomads mod, it'll run just fine. However, (on my end at least) with the mod enabled, even if you pick UEF or any other faction they will still use the default template. According to that forum, the UI for building is messed up too when trying to use regular clicks (Separate issue). The AI doesn't work, at least for me. We should refer Brute to this issue.

**Comment by CookieNoob** [comment]
I didn't mean we should close it at all. I just wanted to say, that it wasn't broken by one of our commits. It was broken before and thus we don't have to search the commit history to look for the reason.

Ofc we need to fix this. (We = jj)

**Comment by JJ173** [comment]
If it's broken and we can't find the commit that breaks it, that's fine. I can re-write the keys for it.
