### ISSUE TITLE
SACUs able to build support factories

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#160]
even those that dont have an egineering suite, only applies for build SACUs not cheated ones

**Comment by CookieNoob** [comment]
@Ithilis when you redo sacus, will there still be presets/upgrade configs that are unable to build stuff?

If not: this issue is solved and can be closed.

**Comment by Ithilis** [comment]
No it will be as other sacu = able build buiding from build whiteout any upgrade. Soo you can close it:)
