### ISSUE TITLE
special ability overlay bug

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#165]
```WARNING: Error running lua command: ...d alliance\gamedata\mohodata.scd\lua\maui\bitmap.lua(35): Expected a game object. (Did you call with '.' instead of ':'?)
         stack traceback:
         	[C]: in function `InternalCreateBitmap'
         	...d alliance\gamedata\mohodata.scd\lua\maui\bitmap.lua(35): in function `__init'
         	...alliance\gamedata\mohodata.scd\lua\maui\checkbox.lua(8): in function `initfn'
         	...data\faforever\gamedata\lua.nx2\lua\system\class.lua(258): in function <...data\faforever\gamedata\lua.nx2\lua\system\class.lua:246>
         	...\gamedata\lua.nmd\lua\ui\ability_panel\abilities.lua(356): in function `AddOrder'
         	...\gamedata\lua.nmd\lua\ui\ability_panel\abilities.lua(338): in function `CreateAltOrders'
         	...\gamedata\lua.nmd\lua\ui\ability_panel\abilities.lua(259): in function `SetAvailableOrders'
         	...\gamedata\lua.nmd\lua\ui\ability_panel\abilities.lua(172): in function `AddSpecialAbility'
         	...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(370): in function <...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua:364>
         	...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(458): in function `OnSync'
         	[string "OnSync()"](1): in main chunk```

happens when watching 5808835 at minute 4:23
(could be observer related, not sure what exactly causes it)

**Comment by TheKeyBlue** [comment]
Don't see any error when watching that replay.
Don't even see the ability panel actually, so not sure how it could cause an error.

**Comment by CookieNoob** [comment]
I just checked it again and it didnt show up when watching the replay. Then I tried to watch the replay from the perspective of some player that build a unit that triggers the ability panel and got this error.

How to reproduce:
go in the persepective of a player that builds a radar. As soon as he finishes, this error shows up.

**Comment by TheKeyBlue** [comment]
It is setup that the abilitypanel isn't created in replays.
But whenever a unit/upgrade for a special ability is created then it tries to create button for it in the abilitypanel. Since the panel doesn't exist it gives an error when it tries to create a button.

Just need to do check if the game is a replay with SessionIsReplay(), before doing AddSpecialAbility (possibly some other functions aswell)

**Comment by TheKeyBlue** [comment]
Wait no don't do that.
Just need to check if the UI control exists or not. 
Thats better than checking for replay.

**Comment by CookieNoob** [comment]
why is that better than checking for replay?
