### ISSUE TITLE
prevent droping navy on land with exp transport

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#167]
when you drop a ship on land, this will happen:
the ship gets dropped and loses hp, dies and starts a sinking animation where it slowly sinks through the ground and vanishes in the abyss.

**Comment by TheKeyBlue** [comment]
Will this also fix issues with dropping land in the water?
Or is that fine? (not sure why dropping navy on land is bad?)

Maybe use description to describe why that is a bad thing :)

**Comment by CookieNoob** [comment]
I updated the description.

dropping land on water, well some landunits can be dropped on water (hover and amphibious units). So either check if there is a non-hover unit on board and cancel the drop order, or just ignore it (like it currently is).

**Comment by JJ173** [comment]
Dropping Navy on Land will destroy the units unless they walk like Salems. Units that aren't amphibious will also get destroyed if they're dropped on Sea.

**Comment by Exotic-Retard** [comment]
yeah so i dont know if its possible to fix this.
you can check the coordinates of the order location (ui side), get the terrain type, then cancel the order if the unit type is not compatible with the terrain type.

sounds like a kinda absurd lot of work and could well include hopping between sim and ui side which also means decreased compatibility and even more work

**Comment by CookieNoob** [comment]
we can just compute the surface height - terrain height and if its zero and the unit category is navy dont drop

**Comment by Exotic-Retard** [comment]
yeah sure but that still requires all of what i said, except you replace GetTerrainType with GetTerrainHeight so yeah that doesnt really help xD
