### ISSUE TITLE
Orbital station shake after big ground explosion

### ISSUE THREAD

**Issue by Ithilis** [Nomads-Project/nomads#169]
What is very wierd when it should be on orbit.

**Comment by CookieNoob** [comment]
not really sure what the issue is, can you elaborate it a bit?

what explodes where and where is the shaking which isnt supposed to be there?

**Comment by Ithilis** [comment]
When is on ground some big explosion, for example T3 artilery projectile fall down. then it shake orbital station as well. but now i realize that it not shake orbital station, but camera, and while its hight it looks like orbital station shake.   

Ok this issue is irelevant to i close it.
