### ISSUE TITLE
upgrade bar hard to see

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#170]
when upgrading a building, the orange upgrade animation covers the upgrade bar a bit, move the upgrade bar a bit down possibly?

**Comment by Exotic-Retard** [comment]
you cant detach the progress bar from the hp bar, you would need to move the hp bar down instead.

**Comment by CookieNoob** [comment]
thats fine I guess, its just not really easy to see the upgradebar on a mex from some of the zoom levels

**Comment by CookieNoob** [comment]
after removing the flashing, its not an issue anymore
