### ISSUE TITLE
SACus have horible voice!!! need remove.

### ISSUE THREAD

**Issue by Ithilis** [Nomads-Project/nomads#175]
naaach i was think that brute remove it! shize i hear it again... 

nomads sacus talk, while other sacus obviosly not. This should not exist if its not enought that sacus are super ugly, they also growl!

**Comment by CookieNoob** [comment]
@Ithilis set the option "select sounds" in gameoptions > sounds to "simple" instead of "full" and you will not have this issue. This is actually the default value for the option so this issue is really not an issue.
