### ISSUE TITLE
TML uses white unit preview picture

### ISSUE THREAD

**Issue by Ithilis** [Nomads-Project/nomads#178]
Should be same color as other building

**Comment by CookieNoob** [comment]
this is actually not so easy... the other unit pictures use the old orange texture. It would probably be better to replace all of these pictures with new ones that use the black texture.

To do that: place a unit on a maximally flat and homogeneous terrain, make a screenshot and delete the background in some graphic program, then replace the old unit picture with the new file.

**Comment by Exotic-Retard** [comment]
" CookieNoob assigned CookieNoob and unassigned CookieNoob 13 hours ago"

what happened here xD

**Comment by CookieNoob** [comment]
I decided it was too much work and then did it anyway xD
