### ISSUE TITLE
NUKE explosion visual efect

### ISSUE THREAD

**Issue by Ithilis** [Nomads-Project/nomads#179]
loks so amazing! best nuke,  except shity explosion on end, its same as on acu explosion.   Jast remove explosion on end and it will looks like 5time better.

**Comment by CookieNoob** [comment]
I wouldnt mind keeping the explosion at the end, but add the fire balls that fly away (like in the acu explosion) and remove the nomad logo shape fire... some fire is ok but not in the shape of the nomad logo xD
