### ISSUE TITLE
T3 static arty lose focus when ground firing

### ISSUE THREAD

**Issue by shalkya** [Nomads-Project/nomads#183]
they only fire once or twice before stopping to fire when they are ground firing.

**Comment by CookieNoob** [comment]
This is intended. It loses its target after 35 seconds, otherwise it wont retarget anything automatically when it destroys something.

**Comment by shalkya** [comment]
so you mean it is actually impossible to ground fire somewhere for a longer period of time than 35sec ? this seems to be weird way to fix other issue. 
if someone tries to ground fire, for any reason, i guess he expect the arty to behave like any other unit...
