### ISSUE TITLE
ACU black hole remove all reclaim nearby

### ISSUE THREAD

**Issue by shalkya** [Nomads-Project/nomads#185]
can even kill an exp reclaim

**Comment by CookieNoob** [comment]
it doesnt. The reclaim is sucked in the blackhole remainder which is this glowing spere

**Comment by shalkya** [comment]
yeah but it remove the reclaim in the end = kill the reclaim.
or there is a way to make the reclaim pop up ? reclaiming the orb doesn't give you any reclaim.
