### ISSUE TITLE
Attack icon bug (unknown reason)

### ISSUE THREAD

**Issue by Ithilis** [Nomads-Project/nomads#188]
This is how it looks like: 
![attact icon bug](https://cloud.githubusercontent.com/assets/9669021/23098390/71a0fea0-f64c-11e6-84bd-92cf48f91374.png)

when i attack with artilery (but also happend with other units) then sometime in unknown situation on air under unit occur attack icon that are diferent as normal attack icon (by more darker color) and mainly should not be on that place. Also there is no reason to show this icon on that time (becsaue i dont setup shift to see comands). 

For this is probably responsible artilery support that retarget artilery units and show new target. But this is only qualitative estimate of reason.

**Comment by CookieNoob** [comment]
what is the bug here? thats the arty support ability...

**Comment by Ithilis** [comment]
The bug there is taht this icon should not show. While its internal think that retarget projectile and for player it get 0 useful information only confuse him what is that. 

And then icon is diferent as normal atack icon. 
It levitate on air ower target. 
Occur independent on player maners. 

So it should not be there, but i dont know how to remove it.

**Comment by Ithilis** [comment]
From conversation why it still related and should be changed.: 

artilery have own target, and is trying to hit it.   but it have firing randomnes.   what arty suport do is that it lower firing randomnes, so its same as before try to hit that target so have attack icon with new retarget is super ussles why it still try to hit same target as accurate as can. and it dont even mean that it hit place where is new attack icon occur  by arilery suport.   while even when it have lowered firing randomnes it still have some and still miss some shots that wil not fall into that icon. so it basicly say again that something is shooting on this place.   what is even worse as normal attack while that have line betwen units and its target.   so its obvious what is going on there is only some attack icon that is not obviously related with any unit.   and say same information as artilery attack comand do. 

and also say it in more uggy way when that icon levitate on air and have diferent color and is not linked with shift as all other comands.   so this is at first buged, and at secnd ussles, at thith it confuse and not add nothing positive in.

**Comment by CookieNoob** [comment]
`The bug there is taht this icon should not show` so its not a bug but a request to change the appearence of the effect.

`what arty suport do is that it lower firing randomnes` thats not how it works

The icon shows the effect of arty support, that's why it will stay for now and eventually will be replaced with a target laser.
