### ISSUE TITLE
reduce particle count of warp-in animation

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#205]
the warp in animation of the acu generates a lot of particles, exceeding the maximum particle count easily when there are multiple nomad players.

Reduce the number of particles involved

**Comment by Exotic-Retard** [comment]
also reduce the duration of the dust - normal factions have an effect lasing for a very short time, theres no need to have a total dustcloud over our base for a few minutes which doesnt even look good and intersects with meshes in an ugly way.
