### ISSUE TITLE
rename mass fab to match the other factions

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#211]
currently the name of the massfab is inb1103 while the other factions have i.e. uab1104, this will make the all faction templates not work with mass fabs

its no problem to change the name since there is no inb1104.

**Comment by Ithilis** [comment]
there is also more building as this. when you look into my merge buiding comits i make notes aboute every building that have bad coding, that is diferent as fa use.   

On units is absoluthly mesch. but on building its only about 5 of them, so it should worth to rewrite it as well..
