### ISSUE TITLE
sacu leaves not enough reclaim

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#213]
reclaim values of the sacu wrecks are not 81% of the mass value of the unit.

**Comment by Exotic-Retard** [comment]
are we sure this is not due to some lack of price adjustments for presets or something?
the 81% comes from scripts, unless there is something specifically overriding this code.

i dunno if the presets code is in nomads but its also now in faf so if its not been done yet it needs a refactor

**Comment by CookieNoob** [comment]
the preset code is fine, its this line here:
https://github.com/Nomads-Project/nomads/blob/develop/units/INU0301/INU0301_unit.bp#L1840

**Comment by Ithilis** [comment]
i will need redig sacus completly once we will have capacitoator upgrade change

**Comment by CookieNoob** [comment]
for now, I will adjust the number to the correct value though
