### ISSUE TITLE
t3 static orbital arty satellite not transfered to other player when arty is given

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#220]
if the recipent is nomad, the orbital frigate will just build a new sat.

we should give the sat together with the arty building

**Comment by TheKeyBlue** [comment]
Could hook OnGiven or add an OnGiven-Callback

https://github.com/FAForever/fa/blob/74ba7f2d3f2e29bd301283dd0036889f71ccb0ed/lua/sim/Unit.lua#L896

**Comment by CookieNoob** [comment]
I think adding the callback is the best solution
