### ISSUE TITLE
Transport has no "Transport full" announcement?

### ISSUE THREAD

**Issue by TheKeyBlue** [Nomads-Project/nomads#229]
Like the description says, usually you have a voice that says that your transport is full when you try to load up more units then it can carry.
But for nomads transport it doesn't do that.

**Comment by TheKeyBlue** [comment]
Okay update: it seems that the sound doesn't work until you spawn a different kind of transport and have that transport trigger the 'transport full' sound.

So how to replicate: 
spawn Nomads T1 transport, spawn a lot of engineers.
Try to load all of them in the transport -> hear no sound
spawn different kind of transport (other kind T1 or T2)
Try to load all engineers in the Nomads T1 transport again -> hear no sound
Try to load all engineers in the 2nd transport -> hear sound
Try to load all engineers in the Nomads T1 transport again -> hear sound

**Comment by CookieNoob** [comment]
wtf

**Comment by CookieNoob** [comment]
yea I can confirm that, it doesnt play a sound until you spawn a second transport... I have no idea what could cause this...

**Comment by JJ173** [comment]
Crazy update: When I tested this, I blew up the first transport and it didn't create a wreckage.

**Comment by JJ173** [comment]
Narrowed it down. The issue only happens with a T1 Nomad Transport. I spawned a T2 first and it worked fine. If you spawn a T1 first, it doesn't work until you follow the replication steps.

**Comment by JJ173** [comment]
Fixed 👍
