### ISSUE TITLE
gate decal stays beyond 10 minutes

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#231]
it disappears for the other factions after that time.

**Comment by Exotic-Retard** [comment]
wont fix? :( why?

**Comment by CookieNoob** [comment]
because the code it correct, the game just decides to do something else for random reasons...
the time is set here:
https://github.com/Nomads-Project/nomads/blob/develop/effects/Entities/Meteor/Meteor_script.lua#L27
the decal is created here:
https://github.com/Nomads-Project/nomads/blob/develop/effects/Entities/Meteor/Meteor_script.lua#L220

however, it is persistent instead of vanishing and changing the value manually to something else will either make it not appear at all or stay persistent.

I dont know what the problem is and it is quite irrelevant.
