### ISSUE TITLE
nomad taunts for other localizations

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#268]
for now, just copy the US taunts to the other localizations.

**Comment by TheKeyBlue** [comment]
Do you need to have non-US taunts?
Since FA also only has US Voice overs anyway?

**Comment by CookieNoob** [comment]
there was a player complaining about not hearing any voice output while using the 'DE' (german) localization. The other (standard) taunts do work though (so he sais).

I dont think FAF adds new soundbanks for the taunts?

**Comment by TheKeyBlue** [comment]
Oh? I looked at my SCFA installation folder and only had voice/US folder. No other languages.
Thats what i meant with FA only having US VOs.

If its an actual issue then i guess you'll have to do that.

**Comment by Exotic-Retard** [comment]
no point translating if there isnt an audio version translated too since loc changes taunt audios too
