### ISSUE TITLE
t2 maa range and projectile speed too large

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#270]

**Comment by Ithilis** [comment]
The issue with nomad flak is taht it haev 3 projectile with relatively huge angel what is bigger on long range. so depend on situation but on small range it have cca 25% more dps and on hight range about 35% less dps. that was done by making taht unit diferent as other flaks that are kinda generic. 

So we should make it more like other flaks what should be about lower projectiles angle, decrese speed and range and it should be fine.
