### ISSUE TITLE
prevent t1 arty from moving into units when on attackmove and air is present

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#282]
currently the arty weapon is disabled when air is close and the arty will suicide into enemy ground units. While on attack move it should keep its distance like it would in the arty mode.

**Comment by Exotic-Retard** [comment]
ok so for reference we should be using code similar to the switching weapons used on the cybran maa and cruiser

the key part here is that the primary weapon is always enabled (the target tracker) which is what the game uses to determine the attack move radius.

after that you can put whatever toggle rules you want on there. in this case i would try to check the layer of the target being targetted by the target tracker, and enable the appropriate weapon automagically - default is auto, but you can override it with an attack order.

also something else to consider as a potential option is having all weapons enabled all the time so it can fire at air and ground simultaneously. just an idea. might sound op but im not sure it is tbh.
