### ISSUE TITLE
Orbital Frigate's Thruster Effects only visible in vision range of player

### ISSUE THREAD

**Issue by JJ173** [Nomads-Project/nomads#289]
The ship's new FX only show when it's not in Fog of War. If the player has a clear view of the ship moving within a view range of a unit, they can see these FX. If the ship is moving through an area covered by Fog of War, they can't see the FX. Needs fixing.

**Comment by CookieNoob** [comment]
oh xD ok yea we can give the frigate vision while moving or maybe there is another way to make it visible... nuke effects are visible to everybody as well...

**Comment by CookieNoob** [comment]
I'll look at this later today
