### ISSUE TITLE
Remove Impact decal from Destroyer

### ISSUE THREAD

**Issue by speed2CZ** [Nomads-Project/nomads#300]
It looks ugly especially when hitting naval targets. But considering it's high fire rate it's useless anyway.

**Comment by CookieNoob** [comment]
The destroyer does damage over time after the initial hit. I agree that the effect size can be reduced a bit, but I wouldnt remove it.

**Comment by speed2CZ** [comment]
Currently its everywhere if you have just couple of them. Disabling ot on water would be a good start as it looks stupid spawning at the sea floor under the target
