### ISSUE TITLE
t3 arty doesnt receive pgen adjacency buffs

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#303]
since the arty satellite is a proxy unit that (obviously) is not adjacent to the pgens surrounding the arty building, the ROF is not adjusted due to pgen adjacency.

**Comment by Exotic-Retard** [comment]
i dnot know off the top of my head but it should be possible since the arty just relays to the sat when its reloaded, so making the ground building reload faster should work.
