### ISSUE TITLE
right barrel of t3 heavy tank misses small units

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#45]
the two gun barrels are always parallel and the targeting is done by aligning the left barrel on the target. Thus small targets wont be hit by the right barrel.

only really relevant against labs (not the most important unit in t3 stage...)

**Comment by Exotic-Retard** [comment]
needs to have dual manipulators set up, see ilshavoh for reference, that also has 2 guns.

it will aim each one slightly differently to hit closer targets.

**Comment by CookieNoob** [comment]
I tried that just now and I failed fixing that... the unit already uses dual manipulators (actually it has its own version of it). I tried setting it up like the ilshavoh (by disabeling the alternative version of the dual manipulators) but I couldnt make it work...

**Comment by Ithilis** [comment]
its not onyl small units it miss also big units. Will try to check it.

**Comment by CookieNoob** [comment]
relevant code is in nomadhook\lua\sim\weapon.lua line 140 - 170
