### ISSUE TITLE
Intel probe, re-upgrading acu abuse causes error

### ISSUE THREAD

**Issue by TheKeyBlue** [Nomads-Project/nomads#54]
I tried to abuse the low cost intel probe acu upgrade by removing the upgrade and upgrading to it again with a t3 acu.
When you reupgrade it you can again select the eye and click on the map, but instead of a new probe, nothing happens and you get an error in the log.

Would be ideal if this was simply not possible and you saw disabled button + cooldown after getting the upgrade again.

**Comment by CookieNoob** [comment]
is related to one of the fix-me
