### ISSUE TITLE
ACU capacitator needs improvement

### ISSUE THREAD

**Issue by TheKeyBlue** [Nomads-Project/nomads#55]
So i tried using the capacitator and it is in need of fixing/improvement

- [ ] Disable the capacitator button when capacitator is unavailable (like the overcharge button)

- [x] Acu has both capacitor % filled icon and fuel % filled icon on unit stats/description/... , while 1 should suffice.

- [ ]  Capacitator bar and cap/fuel % info disappear when it is completely empty, instead of just an empty bar and a 0% icon
- [x] Make it obvious in description that the capacitator bar only fills whenever you are overflowing energy. (does this use energy? should be cause you'll be sharing overflow with your allies, maybe also let it fill faster when you have more overflow?)
- [x] Capacitator can loses 2% per x time of its storage while you aren't overflowing. Needs to be somewhere in description too (could have acu produce more e during this, so the e goes somewhere?)

- [x] Capacitator description is wrong. It buffs intel, regen and buildpower (I think)

**Comment by CookieNoob** [comment]
capacitor is filled by power overflow I think

**Comment by TheKeyBlue** [comment]
mmh ok, you seem to be right about that. I'll fix the first post then.

**Comment by CookieNoob** [comment]
I updated the initial post

**Comment by JJ173** [comment]
Capacitor should be disabled when upgrading ACU. Speeds up the upgrade quite rapidly. Seems a bit OP.

**Comment by CookieNoob** [comment]
dissipation of the stored charge is intended (when you look at the blueprint of the acu)

**Comment by CookieNoob** [comment]
note that the disabling of the overcharge is in lua\sim\defaultweapons.lua and is called PauseOvercharge

**Comment by CookieNoob** [comment]
got this error (no time to investigate atm):
WARNING: Error running lua script: e:\gits\fa\lua\aibrain.lua(4534): attempt to perform arithmetic on a nil value
         stack traceback:
         	e:\gits\fa\lua\aibrain.lua(4534): in function `CapacitorGetUnitEnergyDrainPerTick'
         	e:\gits\fa\lua\aibrain.lua(4422): in function `OnCapacitorUnitChargingState'
         	e:\gits\nomads\lua\nomadutils.lua(1798): in function <e:\gits\nomads\lua\nomadutils.lua:1788>

**Comment by Ithilis** [comment]
This function should be rework and move into upgrade. 

Already it have lot and lot of problems main is that its potencial big advantage ower oter factions or it must be kind of ussles ability (both of then are bad balance wise) and secdon is that its very diferent from other acus what make it hard to implement. Another problem is that it work from energy what in start nearly none have in storages. Later its ussles. Also it have multiple buffs that none see as real impact, so its only something that you click and hope that it do somethign but you realy dont know what reasult it have. Also capacitator on sacu is boosting everything somehow and you have rely not clue what all it change and how. So on scu it should be +- sane as on ACU. But will get different (double) value on same functions. 

It should be move into speed upgrade (replace it) with cost 800m where with 10s usable time and 20s reload time cost 4000e where will add:

more speed 1,7->2,5, +50%
less reload time 1,5s ->1s +50%
aoe 0->1.5
change OC into nomads style with multiple shots
increse visual intel 26 ->39 +50%
add regeneration +30hp/s

**Comment by Ithilis** [comment]
This will be probably for later discusion, but I have lot of good arguments for why:

capacitator acces should be as upgrade (will go on speed upgrade place, where move speed bust will be linked with capacitator as well).   So when you will do this, think also about that some stuff will not be necesary while its as upgrade that is on click and consume X energie isnted of drain wasted e.
