### ISSUE TITLE
naval units sinking needs refactor/fix

### ISSUE THREAD

**Issue by Exotic-Retard** [Nomads-Project/nomads#56]
the nomads navy is pretty buggy in that regard - half of the units dont create wrecks, the subs catapult at absurd speeds and some of them sink absurdly slowly instead.

it might be due to out of date kill sequences, need to check those. and make sure that it doesnt use its own sinking method when we have the sinker projectile for faf.

**Comment by CookieNoob** [comment]
currently nomads use their own sinking animation thread:
https://github.com/Nomads-Project/nomads/blob/31b45d88c77d6d42c0f02294934f11148a24b611/lua/nomadunits.lua#L349

it might be better to just use the FAF one with the sinker script
https://github.com/FAForever/fa/blob/6bfdf7f04f5fd3a09d02884d68dc4d68a1a54666/lua/sim/Unit.lua#L1559

https://github.com/FAForever/fa/blob/287276db8ef4db691da8f54ba477e77583666695/projectiles/Sinker/Sinker_script.lua
