### ISSUE TITLE
intelboost not working

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#60]
having a radar and power in storage allows to increase the radar range. However, the ability cursor has a "disabled" sign on top of it. The ability seems to be not working.

**Comment by Exotic-Retard** [comment]
can confirm bug, also can confirm bullshit - fir radar i spawned didnt work, but second one did, and deleting first one didnt change this, so yyyyyyyyyeah

i.e. it seems to work at least sometimes
