### ISSUE TITLE
remaining fuel is not shown on airplanes

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#63]
airplanes should have an indicator (a timer) that shows for how long the fuel will suffice. Nomad units have a fuel bar, but this is missing.

**Comment by CookieNoob** [comment]
the problem is that the UI functions that generate the respective elements in the UI are destructively hooked and thus this element (as well as build power) are overwritten. Needs a refactor of 
https://github.com/Nomads-Project/nomads/blob/81510467e25a5c36fdeb973b02e4d964a0352677/balancehooks/FAFhook/lua/ui/game/unitview.lua

same issue as #71

**Comment by Exotic-Retard** [comment]
probably related issue - the veterancy icon is incorrect for units - its got the missile (for ammo usually) there instead of the chevron thingy
