### ISSUE TITLE
T4 missile tank EMP missiles not disappearing on impact with unit

### ISSUE THREAD

**Issue by RK4000** [Nomads-Project/nomads#64]
the missiles continue to do damage every tick after they collide with a unit. (tested on GC).

error in log: 
WARNING: Error running OnImpact script in Entity /projectiles/nempmissile1/nempmissile1_proj.bp at 25c1af00: ...der forged alliance\new folder 2\fa\lua\sim\unit.lua(2355): table index is nil

**Comment by JeroenDeDauw** [comment]
Probably similar issue as https://github.com/Nomads-Project/nomads/issues/34
