### ISSUE TITLE
uef t2 gunship has ambigious class definitions

### ISSUE THREAD

**Issue by Exotic-Retard** [Nomads-Project/nomads#66]
this is because its also a transport. this means that since nomads hooks OnKilled its defined in 2 places and not merged correctly.

its when the transports have been changed to enable wreck dropping.

either the unit script for the gunship needs to be hooked, or the hook for air unit OnKilled needs to be changed or possibly both.

**Comment by speed2CZ** [comment]
You know what helps in the issue description? link to the code

**Comment by CookieNoob** [comment]
I dont have this error anymore. Since we didnt change anything about this, I checked different branches of the FA repo and the current version of deploy/FAFdevelop doesnt have this issue anymore.

**Comment by CookieNoob** [comment]
I wasnt able to pin down the exact commit that fixes that though. Maybe @speed2CZ can have a look ^^

**Comment by CookieNoob** [comment]
this issue is moved to #104
