### ISSUE TITLE
add descriptions for enhancements of the sacus

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#68]
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000il
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000se
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000sepa
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000isb
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000acap
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000acu
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000rae
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000rar
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000larg
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000ses
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000rag
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000rag2
WARNING: No description found for unit: \000inu3001_Default\000 enhancement: \000lar

this happens for all different presets (the texts are there, but only for the basic sacu model)

**Comment by Exotic-Retard** [comment]
or we could change it to look for the things in not the inu3001_Default blueprint

perhaps it should point to just inu03001

**Comment by CookieNoob** [comment]
I am not sure why it doesnt do that already... I compared the bp to the UEF sacu and its more or less the same. There is no inu3001_Default blueprint or any of the other blueprints (i.e. inu3001_Rambo,...)

**Comment by JJ173** [comment]
Error still unknown. I followed all templates to see what was going on and logging didn't provide any useful information (yet).

**Comment by CookieNoob** [comment]
interestingly, the quantum gate build options (in hotbuild) are indeed the bp with the _blabla
https://github.com/Nomads-Project/nomads/blob/31b45d88c77d6d42c0f02294934f11148a24b611/nomadhook/lua/ui/game/buildmodedata.lua#L239

so there seems to be some script generating these bp from the original blueprint

**Comment by CookieNoob** [comment]
maybe this is related:
https://github.com/FAForever/fa/blob/287276db8ef4db691da8f54ba477e77583666695/modules/buildingtab.lua#L94

**Comment by TheKeyBlue** [comment]
This has something todo with this:
https://github.com/Nomads-Project/nomads/blob/master/nomadhook/lua/ui/game/unitviewDetail.lua#L132

The code uses the fact that all fa SACU are 0301 and not 3001 like for nomads, so it doesn't work properly.
Easy solution: rename inu3001 -> inu0301 ?

**Comment by speed2CZ** [comment]
having the units named the same way or other 4 faction is a good idea, with that I'd like to say that INL is better than INU :D if anyone feels like having too much free time

**Comment by Exotic-Retard** [comment]
the fact that the 'mads have completely messed up unit naming conventions is quite annoying yes

**Comment by CookieNoob** [comment]
"I" actually makes sense (forged alliance had X as the first letter to distinguish from normal sup com)
"N" also ok (faction letter, aeon has a, ....)
rest is messed up, I agree xD

**Comment by Exotic-Retard** [comment]
im ok with the i and n but not the everything else too xD
