### ISSUE TITLE
merge balancehook/units into units/

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#73]
currently the blueprints of the nomads units are split into multiple parts. The wreckage part as well as some economy parts are in balancehook while the rest of the blueprint is in units/

Since we are only supporting FAF with our version we should drop this split. Can be simultaneously done with a rebalance of the units.

**Comment by speed2CZ** [comment]
No, first you want to merge and then you want to start doing changes in different commit

**Comment by CookieNoob** [comment]
its finished
