### ISSUE TITLE
find reason for nomads lobby not loading

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#8]
maybe related: find out why it takes so long to load the lobby when launching from the executable

**Comment by CookieNoob** [comment]
reason: init file broken xD

**Comment by Exotic-Retard** [comment]
huh
tell me more, tbh i dont know that much about init files let alone the nonsense i did to get nomads to work
but w.e. we can try xD

**Comment by Exotic-Retard** [comment]
just for info: the power of ithilis prevailed! xD

**Comment by CookieNoob** [comment]
nvm its something else:
warning: Error running Hosting script in CScriptObject at 11818dc0: attempt to use as string a nil value
         stack traceback:
         	[C]: in function `SetText'
         	...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua(2690): in function `SetTextLine'
         	...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua(2709): in function `CalcVisible'
         	...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua(3132): in function `RefreshOptionDisplayData'
         	...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua(2729): in function `CreateUI'
         	...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua(3810): in function <...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua:3716>
         	[C]: in function `HostGame'
         	...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua(588): in function <...faforever\gamedata\nomads.nmd\lua\ui\lobby\lobby.lua:584>

**Comment by CookieNoob** [comment]
this is probably fixed by using the normal FAF lobby and ignoring lobby.lua entirely see https://github.com/CookieNoob/nomads/pull/51

**Comment by CookieNoob** [comment]
if there are some problems we cant see them before putting it up as featured mod. Atm there is full compatibility with the lobby
