### ISSUE TITLE
random doesnt yield nomads anymore

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#80]
regression from original nomads version due to the refactor (i.e. removal of lobby.lua)
@TheKeyBlue 

needs to be changed when replacing the random faction symbol #50

**Comment by TheKeyBlue** [comment]
Are you sure?
Because i just did a game with 16 random faction AI's and there where some nomads there.
The lobby code also shows that nomads should be included.

**Comment by CookieNoob** [comment]
lel maybe I am wrong, need to test it... I tried it 3 times in a row with 16 ais (first time was to test retards hover animations) and in none of the games was a random nomad ai xD maybe just a coincidence. I will test it again when I am home.

**Comment by CookieNoob** [comment]
xD omg. I tested it again and got several nomad ai players. Its a non-issue.

the propability for this being a false alarm is really low though xD

it was with 11 AIs and 3 times in a row, so 0.8^33 = 0.06%
