### ISSUE TITLE
acu and sacu able to build support factories without HQ

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#91]
when I fixed the upgrade bug with support factories #22 I checked engies and factories but forgot to check acu and sacu.

ofc it didnt work there xD

sacu is fixed in the branch bugfix/acu-and...

acu however is able to select the support factories while upgrading. after completing the update it's correct, but during upgrade these factories are shown. Not sure why (yet)

**Comment by CookieNoob** [comment]
the ability of the acu to build stuff of higher tech while upgrading the tech upgrade comes from notify. Unfortunately do all units have the tag "nomad" while the faction name is "nomads"
thus notify tries to restrict the support factories of "nomads" and the relevant factories stay unrestricted

**Comment by Exotic-Retard** [comment]
maybe fixed in the bullshit commit i made?

**Comment by CookieNoob** [comment]
yes it is
