### ISSUE TITLE
Buff section of t3 arty and orbital cannon dont match

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#93]
WARNING: INO2302: Buffs sections in parent and slave unit blueprints do not match

this happens when a satellite is assigned to a new t3 arty ground station.

**Comment by CookieNoob** [comment]
comes from here:
https://github.com/Nomads-Project/nomads/blob/959d20254eac44b9c7d27a9e494dc2e78c498fdc/units/INO2302/INO2302_script.lua#L67

find out whats the purpose of this check

**Comment by TheKeyBlue** [comment]
I'm guessing that it is so you don't accidently change one but not the other and then are baffled with the unexpected results? Since they are basicly the same unit.

I changed the check a little to make it work, (which isn't really safe to be fair) but i'm assuming ithilis or someone else undid the changes to either blueprint so the values have become different again.

**Comment by CookieNoob** [comment]
I removed the check since it doesnt do anything, except throwing an error in the log.

**Comment by Exotic-Retard** [comment]
well actually this is kinda a thing - what this means is that we should reset any buffs to the sat and the self.XP value on arty building death.

ok maybe for nomads its not a huge issue but for other mods that fuck with vet this would cause issues

**Comment by CookieNoob** [comment]
I am not sure why this is needed. The sat is not targetable and thus vet doesnt matter. The groundstation always starts from 0 XP...

**Comment by Exotic-Retard** [comment]
"ok maybe for nomads its not a huge issue but for other mods that fuck with vet this would cause issues"
things like totalveterancy which give dps rof and more things bscly means this sat keeps all the vet and cant die. its mod compatibility

**Comment by CookieNoob** [comment]
kk, so we set the xp back to 0 when we assign it to a new station.

**Comment by CookieNoob** [comment]
as it turns out, the sat doesnt gain any xp at all... I will add vet for the satellite and a clear function when the station dies.

**Comment by Exotic-Retard** [comment]
you also need to clear its buffs table on death
