### ISSUE TITLE
work out how to deal with shaders in mesh.fx

### ISSUE THREAD

**Issue by Exotic-Retard** [Nomads-Project/nomads#99]
we need help on this. 
theres pretty much no control over this element of the mod atm. and it contains inconsistent names at the very least that need to be fixed need someone with shader knowledge to teach us how its done or fix it, or even better both

**Comment by CookieNoob** [comment]
what else is needed for this than deleting the file before the game starts?

**Comment by Exotic-Retard** [comment]
this is not with deleting the file, this is about having control over it
for a start we need to start using "nomads" and not nomad consistently, next this will let is do graphical improvements on the faction, possibly doing things we couldnt do before.

need someonelike ozonex to help us xD

**Comment by CookieNoob** [comment]
ok turns out the shader is in the mesh.fx of normal FAF xD

**Comment by Exotic-Retard** [comment]
ok in other new HERO ThomasHiatt is helping out with the shaders now, all questions on those go to him.
we need to take the shaders under our control now since nomads_mesh.fx seems to do nothing.

then we can look at tweaking them

**Comment by CookieNoob** [comment]
nomads_mesh.fx was added by me, introducing the nomad shader techniques to fix crashes in the map editor when nomad units were added. It is not part of the distributed nomad mod on the server. it is not even loaded when the game starts. Of cause it does nothing xD
